#! /usr/bin/perl -w

# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT license.

# A log of 1 million artificial queries (generated by queryLogEmulator.exe in SynthaCorpus)
# is assumed to exist in ../test_queries/emulated_log.q.  The job of this script is to
# extract/create a number of derivative query files:
#
#
# emulated_log_100k.q                      # The first 100,000 queries
# emulated_log_100k_autopartials.q         # emulated_log_100k.q expanded to include succeeding keystrokes
# emulated_log_10k.q                       # The first 10,000 queries
# emulated_log_1k.q                        # The first 1,000 queries
# emulated_log_four_full_words_10k.q       # The first 10,000 queries containing exactly four words. 
# emulated_log_four_words_with_operators.q # The four-word queries with randomly inserted operators.


$stem = "../test_queries/emulated_log";

die "Can't read $stem.q\n"
    unless open R, "$stem.q";

die "Can't write to ${stem}_100k.q\n"
    unless open W100, ">${stem}_100k.q";

die "Can't write to ${stem}_10k.q\n"
    unless open W10, ">${stem}_10k.q";

die "Can't write to ${stem}_1k.q\n"
    unless open W1, ">${stem}_1k.q";

die "Can't write to ${stem}_four_full_words_10k.q\n"
    unless open FW10, ">${stem}_four_full_words_10k.q";

# Check whether the other scripts we need are here.

die "./make_autosuggest_robustness_queries.pl isn't here or isn't executable\n"
    unless -x "./make_autosuggest_robustness_queries.pl";

die "./randomly_insert_qbasher_operators.pl isn't here or isn't executable\n"
    unless -x "./randomly_insert_qbasher_operators.pl";




print "\nReading $stem.q and making subset files ...\n\n";

$qcnt = 0;
$four_wd_cnt = 0;
while (<R>) {
    # Input query log may contain blank lines.  Don't allow them in the subsets
    next if (/^\s*$/);
    if (++$qcnt <= 100000) {
	print W100 $_;
	if ($qcnt <= 10000) {
	    print W10 $_;
	    if ($qcnt <= 1000) {
		print W1 $_;
	    }
	}
    }

    @f = split /\s+/;
    if (($#f == 3) && (++$four_wd_cnt <= 10000)) {
	print FW10 $_;
    }	
}

close(W100);
close(W10);
close(W1);
close(FW10);
close(R);


print "Generating the autosuggest test file ...\n\n";

$cmd = "$^X ./make_autosuggest_robustness_queries.pl < ${stem}_100k.q > ${stem}_100k_autopartials.q";
$code = system($cmd);
die "$cmd failed with code $code\n"
    if $code;

print "Generating the test file with randomly inserted operators ...\n\n";

$cmd = "$^X ./randomly_insert_qbasher_operators.pl < ${stem}_10k.q > ${stem}_four_words_with_operators.q";
$code = system($cmd);
die "$cmd failed with code $code\n"
    if $code;

print "The following derivative query sets written:
   ../test_queries/emulated_log_100k.q
   ../test_queries/emulated_log_100k_autopartials.q
   ../test_queries/emulated_log_10k.q
   ../test_queries/emulated_log_1k.q
   ../test_queries/emulated_log_four_full_words_10k.q
   ../test_queries/emulated_log_four_words_with_operators.q

    ";

exit(0);
